=== Mariam-Mokhtar/XML_Labs_ITI/Lab3/Part1/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2023 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="country"/>
				<xs:element ref="city"/>
				<xs:element ref="region"/>
				<xs:element ref="street"/>
				<xs:element ref="building-no"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="addresses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="building-no">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="18"/>
				<xs:enumeration value="92"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="city">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Alexandria"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="country">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Egypt"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="email">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Mariam@gmail.com"/>
				<xs:enumeration value="Mokhtar@gmail.com"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="email"/>
				<xs:element ref="phones"/>
				<xs:element ref="addresses"/>
			</xs:sequence>
			<xs:attribute name="isbn" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="_1"/>
						<xs:enumeration value="_2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="employee" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Mariam"/>
				<xs:enumeration value="Mokhtar"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="phone">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_phone">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="home"/>
								<xs:enumeration value="mobile"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="phones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="phone" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="region">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="ElQabry"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="street">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="18 st el-maks"/>
				<xs:enumeration value="92 st el-maks"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="ST_phone">
		<xs:restriction base="xs:string">
			<xs:enumeration value="015011586968"/>
			<xs:enumeration value="015011666968"/>
			<xs:enumeration value="03 4494386"/>
			<xs:enumeration value="03 4495386"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Mariam-Mokhtar/XML_Labs_ITI/Lab3/Part1/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="employee.css"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///F:/xampp/htdocs/xml/Lab3/Part1/employee.xsd">
	<employee isbn="_1">
		<name>Mariam</name>
		<email>Mariam@gmail.com</email>
		<phones>
			<phone type="mobile">015011586968</phone>
			<phone type="home">03 4494386</phone>
		</phones>
		<addresses>
			<address>
				<country>Egypt</country>
				<city>Alexandria</city>
				<region>ElQabry</region>
				<street>92 st el-maks</street>
				<building-no>92</building-no>
			</address>
		</addresses>
	</employee>
	<employee isbn="_2">
		<name>Mokhtar</name>
		<email>Mokhtar@gmail.com</email>
		<phones>
			<phone type="mobile">015011666968</phone>
			<phone type="home">03 4495386</phone>
		</phones>
		<addresses>
			<address>
				<country>Egypt</country>
				<city>Alexandria</city>
				<region>ElQabry</region>
				<street>18 st el-maks</street>
				<building-no>18</building-no>
			</address>
		</addresses>
	</employee>
</employees>
